### ISSUE TITLE
Multi Store Problem

### ISSUE THREAD

**Issue by pandeo** [PHOENIX-MEDIA/Magento-BankPayment#13]
When puting module to multi store, its working fine except after order showing only default bank details.

Like i have 2 websites on 1 admin page.
on 1 website there is company x details
On 2 website there is company z details

When im making order on website nr 2, in admin page it showing me company X details [default value]

**Comment by pandeo** [comment]
Upgrade:
It show correct datas, but what including in "Custom Text" taking default value.

**Comment by MaWoScha** [comment]
In my fork it should be fixed:
https://github.com/MaWoScha/Magento-BankPayment/releases/tag/v1.3.0
