### ISSUE TITLE
Allow Capturing

### ISSUE THREAD

**Issue by sprankhub** [PHOENIX-MEDIA/Magento-BankPayment#16]
Could you set `$_canCapture` and `$_canCapturePartial` in your payment method to true? This would allow people to create invoices with this payment method as open / unpaid, so that they can be captured / marked as paid later on.

**Comment by PHOENIX-MEDIA** [comment]
Thank's for your input. We've released a new version (1.2.0) with a view bugfixes and added your suggestions.
