### ISSUE TITLE
Account Numer & Sort Code removed?

### ISSUE THREAD

**Issue by BSHoneyBees** [PHOENIX-MEDIA/Magento-BankPayment#19]
Just updated this app, it no longer shows the customer Sort Code or Account number to pay only IBAN & BIC? Is there any reason for this? Ideally need to revert to previous version to get this to show on the front end as all our customers are now unable to make payment via this method. It also only shows IBAN & BIC fields in the config.

Dan

**Comment by MaWoScha** [comment]
I (re)added the Sort Code and Account number on PHOENIX-MEDIA/Magento-BankPayment version 1.2.:
https://github.com/MaWoScha/Magento-BankPayment/releases/tag/v1.3.0
Also I tried to add a dependency of bank accounts on order currency!
MaWoScha

**Comment by PHOENIX-MEDIA** [comment]
Hi, We will re-add the fields including an option to show/hide the sortcode and account number shortly.

**Comment by PHOENIX-MEDIA** [comment]
Account number and sort code have been re-added in latest release.
