### ISSUE TITLE
IBAN/BIC current situation

### ISSUE THREAD

**Issue by easyMaxi** [PHOENIX-MEDIA/Magento-BankPayment#4]
Ab dem 1.2, wenn ich richtig informiert bin
With the 1.2 in Germany we changed with SEPA. We now need to show IBAN and BIC instead of the current account details. Is there anything preventing us from standardize this?
## Current:

Kontoinhaber: xxx
Kontonummer:    xxxx
BLZ:    xxx
Bankname:   xxxx

Für internationale Überweisungen benutzen Sie bitte folgende Daten:
IBAN:   xxxx
BIC:    xxxx
## or with no account number:

Kontoinhaber:   xxxx
Bankname:   xxxxx

Für internationale Überweisungen benutzen Sie bitte folgende Daten:
IBAN:   xxxxx
BIC:    xxxx
## My suggestion

Kontoinhaber:   xxxx
Bankname:   xxxxx
IBAN:   xxxxx
BIC:    xxxx

At least for all german customers.

Comments?

**Comment by ppassmannpriv** [comment]
This should be re-adressed. As of February 1 2016 SEPA is mandatory in Germany. The "Für internationale Überweisungen benutzen Sie bitte folgende Daten:" is now obsolete.

**Comment by PHOENIX-MEDIA** [comment]
Finally we've released a new version (1.2.0) where we eliminated the old account details and completely switched to IBAN/BIC.
