### ISSUE TITLE
Email Follow-up 

### ISSUE THREAD

**Issue by Unike-Shop** [PHOENIX-MEDIA/Magento-BankPayment#6]
I think that would be interesting an option to send a Follow-up email to customer after 
example 3 days, usually customer should send a proof of payment to your email or you would need to check your bank account every day to check which order have been paid

**Comment by sprankhub** [comment]
I do not think that this has anything to do with the payment method.

But there are extensions out there for things like that. Shameless self promotion: https://www.modulwerft.com/magento-zahlungserinnerung-mahnung.html
